version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: testtask_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: TimescaleDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: testtask_api
    restart: unless-stopped
    ports:
      - "7035:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=TimescaleDb;Username=postgres;Password=password

volumes:
  postgres_data: