--
-- PostgreSQL database dump
--


-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

-- Started on 2026-08-11 09:18:00

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 24954)
-- Name: Results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Results" (
    "FileName" character varying(255) NOT NULL,
    "DeltaTime" double precision NOT NULL,
    "MinDate" timestamp with time zone NOT NULL,
    "AverageExecutionTime" double precision NOT NULL,
    "AverageValue" double precision NOT NULL,
    "MedianValue" double precision NOT NULL,
    "MaxValue" double precision NOT NULL,
    "MinValue" double precision NOT NULL
);


--
-- TOC entry 218 (class 1259 OID 24948)
-- Name: Values; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Values" (
    "Id" bigint NOT NULL,
    "FileName" character varying(255) NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "ExecutionTime" integer NOT NULL,
    "Value" double precision NOT NULL
);


--
-- TOC entry 217 (class 1259 OID 24947)
-- Name: Values_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Values" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Values_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4854 (class 0 OID 24954)
-- Dependencies: 219
-- Data for Name: Results; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Results" ("FileName", "DeltaTime", "MinDate", "AverageExecutionTime", "AverageValue", "MedianValue", "MaxValue", "MinValue") FROM stdin;
test.csv	600	2024-01-01 19:00:00+07	10	15.166666666666666	15.5	20	10
test_large.csv	840	2024-02-01 17:01:00+07	16.666666666666668	8.44	8.8	15.6	1.1
\.


--
-- TOC entry 4853 (class 0 OID 24948)
-- Dependencies: 218
-- Data for Name: Values; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Values" ("Id", "FileName", "Date", "ExecutionTime", "Value") FROM stdin;
1	test.csv	2024-01-01 19:00:00+07	10	15.5
2	test.csv	2024-01-01 19:05:00+07	12	20
3	test.csv	2024-01-01 19:10:00+07	8	10
4	test_large.csv	2024-02-01 17:01:00+07	10	1.1
5	test_large.csv	2024-02-01 17:02:00+07	12	2.2
6	test_large.csv	2024-02-01 17:03:00+07	15	3.3
7	test_large.csv	2024-02-01 17:04:00+07	8	4.4
8	test_large.csv	2024-02-01 17:05:00+07	20	5.5
9	test_large.csv	2024-02-01 17:06:00+07	14	6.6
10	test_large.csv	2024-02-01 17:07:00+07	18	7.7
11	test_large.csv	2024-02-01 17:08:00+07	25	8.8
12	test_large.csv	2024-02-01 17:09:00+07	30	9.9
13	test_large.csv	2024-02-01 17:10:00+07	22	10.1
14	test_large.csv	2024-02-01 17:11:00+07	19	11.2
15	test_large.csv	2024-02-01 17:12:00+07	11	12.3
16	test_large.csv	2024-02-01 17:13:00+07	16	13.4
17	test_large.csv	2024-02-01 17:14:00+07	9	14.5
18	test_large.csv	2024-02-01 17:15:00+07	21	15.6
\.


--
-- TOC entry 4860 (class 0 OID 0)
-- Dependencies: 217
-- Name: Values_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Values_Id_seq"', 18, true);


--
-- TOC entry 4706 (class 2606 OID 24958)
-- Name: Results Results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Results"
    ADD CONSTRAINT "Results_pkey" PRIMARY KEY ("FileName");


--
-- TOC entry 4701 (class 2606 OID 24952)
-- Name: Values Values_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Values"
    ADD CONSTRAINT "Values_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 4702 (class 1259 OID 24961)
-- Name: IX_Results_AverageExecutionTime; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Results_AverageExecutionTime" ON public."Results" USING btree ("AverageExecutionTime");


--
-- TOC entry 4703 (class 1259 OID 24960)
-- Name: IX_Results_AverageValue; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Results_AverageValue" ON public."Results" USING btree ("AverageValue");


--
-- TOC entry 4704 (class 1259 OID 24959)
-- Name: IX_Results_MinDate; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Results_MinDate" ON public."Results" USING btree ("MinDate");


--
-- TOC entry 4699 (class 1259 OID 24953)
-- Name: IX_Values_FileName_Date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Values_FileName_Date" ON public."Values" USING btree ("FileName", "Date");


-- Completed on 2026-08-11 09:18:01

--
-- PostgreSQL database dump complete
--

